// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVAAtmwE07PwOubdl0B2FlNycbHcfyN8',
    appId: '1:991686930183:android:c51cd2fe5073452e4e5fa2',
    messagingSenderId: '991686930183',
    projectId: 'ecommerce-anly',
    storageBucket: 'ecommerce-anly.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4UMNBgJeslUtSHZDbFiKTkjmDVZkyTU',
    appId: '1:991686930183:web:b9bb62b2468b129f4e5fa2',
    messagingSenderId: '991686930183',
    projectId: 'ecommerce-anly',
    authDomain: 'ecommerce-anly.firebaseapp.com',
    storageBucket: 'ecommerce-anly.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4UMNBgJeslUtSHZDbFiKTkjmDVZkyTU',
    appId: '1:991686930183:web:ca90dca43d8719f04e5fa2',
    messagingSenderId: '991686930183',
    projectId: 'ecommerce-anly',
    authDomain: 'ecommerce-anly.firebaseapp.com',
    storageBucket: 'ecommerce-anly.firebasestorage.app',
  );

}